spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentmate_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.rentmate: DEBUG

